version: '3.8'

services:
  prompt-detective:
    build:
      context: ..
      dockerfile: part2/Dockerfile
    container_name: prompt-detective-api
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - SERVICE_NAME=prompt-detective
      - SERVICE_VERSION=1.0.0
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service-account.json
      - VERTEX_AI_LOCATION=${VERTEX_AI_LOCATION:-us-central1}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - MAX_REQUEST_SIZE=10000
      - REQUEST_TIMEOUT=30
      - MAX_RETRIES=3
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_WINDOW=60
    volumes:
      - ./logs:/app/logs
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/credentials/service-account.json:ro
    restart: unless-stopped
    mem_limit: 512m
    cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - prompt-detective-network

networks:
  prompt-detective-network:
    driver: bridge